language: node_js
node_js:
  - "6.1"

# cache:
#   bundler: true
#   directories:
#     - node_modules

install:
  - npm install

before_script:
  - npm install karma-phantomjs-launcher --save-dev
  - export CONTINUOUS_INTEGRATION=true

script:
  - npm test

after_success:
  "npm run deploy"
